# Generated by Django 4.2.7 on 2023-11-21 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userproject",
            name="current_date",
        ),
        migrations.RemoveField(
            model_name="userproject",
            name="updated_date",
        ),
    ]
