# Generated by Django 4.2.7 on 2023-11-22 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_rename_uuid_achievementhistory_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklog",
            name="current_date",
        ),
        migrations.RemoveField(
            model_name="tasklog",
            name="updated_date",
        ),
    ]
