# Generated by Django 4.2.7 on 2023-11-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_designation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_users",
                to="staff.designation",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.designation",
            ),
        ),
    ]
